Repository Judge-em/api, pull requests merged in 2020-10, with the labels that each got.

#9 Dev database schema
  Storage/JudgeContext.cs
  Storage/Migrations/20201014104223_InitDatabase.Designer.cs
  Storage/Migrations/20201014104223_InitDatabase.cs
  Storage/Migrations/JudgeContextModelSnapshot.cs
  Storage/ServiceCollectionExtension.cs
  Storage/Storage.csproj
  Storage/Tables/Category.cs
  Storage/Tables/Game.cs
  Storage/Tables/Item.cs
  Storage/Tables/Rating.cs
  Storage/Tables/Summary.cs
  Storage/Tables/User.cs
  WebApi/Startup.cs
  WebApi/WebApi.csproj
  WebApi/appsettings.json
Labels: enhancement

#10 Room management and connection
  Core/Core.csproj
  Core/Helpers/CodeGenerator.cs
  Core/Requests/GameCreateRequest.cs
  Core/Requests/ItemCreateRequest.cs
  Core/Services/GameService.cs
  Core/Services/Interfaces/IGameService.cs
  Core/Services/Interfaces/IItemService.cs
  Core/Services/Interfaces/ISummaryService.cs
  Core/Services/ItemService.cs
  Core/Services/SummaryService.cs
  Storage/Repositories/BaseRepository.cs
  Storage/Repositories/GameRepository.cs
  Storage/Repositories/Interfaces/IBaseRepository.cs
  Storage/Repositories/Interfaces/IGameRepository.cs
  Storage/Repositories/Interfaces/IItemRepository.cs
  Storage/Repositories/Interfaces/ISummaryRepository.cs
  Storage/Repositories/ItemRepository.cs
  Storage/Repositories/SummaryRepository.cs
  Storage/ServiceCollectionExtension.cs
  WebApi/Controllers/GamesController.cs
  WebApi/Hubs/GameHub.cs
  WebApi/Hubs/GameHubMaster.cs
  WebApi/Hubs/IGameClient.cs
  WebApi/Startup.cs
  WebApi/WebApi.csproj
Labels: enhancement

#25 Added crud endpoints and swagger doc
  Core/Requests/CategoryUpdateRequest.cs
  Core/Services/CategoryService.cs
  Core/Services/GameService.cs
  Core/Services/Interfaces/ICategoryService.cs
  Storage/Repositories/GameRepository.cs
  Storage/Tables/Category.cs
  Storage/Tables/CategoryRating.cs
  Storage/Tables/Game.cs
  Storage/Tables/Item.cs
  Storage/Tables/Rating.cs
  Storage/Tables/User.cs
  WebApi/Controllers/CategoriesController.cs
  WebApi/Controllers/GamesController.cs
  WebApi/Controllers/HomeController.cs
  WebApi/Controllers/ItemsController.cs
  WebApi/Controllers/RatingsController.cs
  WebApi/Startup.cs
  WebApi/WebApi.csproj
Labels: documentation, enhancement

#29 Dev game categories fix
  Storage/Migrations/20201021165927_AddCategoriesGameRelation.Designer.cs
  Storage/Migrations/20201021165927_AddCategoriesGameRelation.cs
  Storage/Storage.csproj
  Storage/Tables/Category.cs
Labels: bug

#31 Dev authorization
  Authorization/Authorization.csproj
  Authorization/Requests/RegisterRequest.cs
  Authorization/ServiceCollectionExtension.cs
  Authorization/Services/AuthenticationService.cs
  Authorization/Services/Interfaces/IAuthenticationService.cs
  Authorization/Services/Interfaces/IJwtService.cs
  Authorization/Services/JwtService.cs
  Storage/Migrations/20201014104223_InitDatabase.cs
  Storage/Repositories/Interfaces/IUserRepository.cs
  Storage/Repositories/UserRepository.cs
  Storage/ServiceCollectionExtension.cs
  Storage/Tables/User.cs
  WebApi/Controllers/AuthenticationController.cs
  WebApi/Startup.cs
  WebApi/appsettings.json
Labels: core, enhancement

#34 Fixed code generation bug and updated endpoints
  Core/Services/CategoryService.cs
  Core/Services/GameService.cs
  Core/Services/Interfaces/ICategoryService.cs
  WebApi/Controllers/AuthenticationController.cs
  WebApi/Controllers/CategoriesController.cs
  WebApi/appsettings.json
Labels: bug
